// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-UTIQ",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-UTIQ", targets: ["AATKit-UTIQ"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-UTIQ",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATUtiq",
                    "AATUTIQAdapter",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-UTIQ"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATUtiq",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/Utiq.zip",
            checksum: "d7b8f27b5ca7503a632984a43aba8c2a46ce9d4e30892c52fb3171e97d884f71"
        ),
        .binaryTarget(
            name: "AATUTIQAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATUTIQAdapter.zip",
            checksum: "d11e755f4de3eab4835001ed54f5dde25591f27ed5326fcc5554a748dc48ca43"
        ),
    ]
)
