// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-UTIQ",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-UTIQ", targets: ["AATKit-UTIQ"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-UTIQ",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATUtiq",
                    "AATUTIQAdapter",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-UTIQ"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATUtiq",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/Utiq.zip",
            checksum: "8021ec02ffa29be58b0e08e2a380dd55c28f10b9add5685677b7f564779578f8"
        ),
        .binaryTarget(
            name: "AATUTIQAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATUTIQAdapter.zip",
            checksum: "89ea538534c138f4149076b734ac596f67177bc6250c583a6b979ae0ecfb9f14"
        ),
    ]
)
